language: python
python:
- 3.5
install:
- pip install coveralls
script:
- coverage run --source=test setup.py test
env:
  global:
    - GIT_TAG="Commit Travis CI build # $TRAVIS_BUILD_NUMBER ."
    - secure: "aVRUKBWxWt6Ts9FVAMdkBqkyKrChWjPNExmKfdcPlOkW9izUNTk5ee17NcxTnvV05lzlGD+hegr4gJpaztX3syoZmSDT4skgyVS9hMmtKUIoFJnVVgngN0CvhQdfK9vG/0OJYpLCbQz6iV8TiRDDjpsWH2Ix77xB4tg19SVdeSJvdYE7aVcRcBC0fXzKoF6PpDYpswcZrYLEv81SLHF7cMwiBS+Ptw2Rakxj8ZCdezwPy4+L722VodjeL49Ezx+2oENuR7COzff8527s78IPZQTFu/TxMOcolM5qXn/0oODi8JWE6S2agt3rbRwjp2UaJB41X9yL4d7hvh/CYXkXVf4DGCgcaq0kK5kE5qjMECUk0uNoAMB5W2AZ8T86xXqowyYkvwZseLd/+x+PSuLfHmAyiAH8ZXeefr7DTm4qJLfRxXn/Sh3TJ40JI5imVn3vbsHn6J/scoIKs5brgRUb//jYDMDCHPX6XqnWfnrVM8ou4sl4t364IHHFwiWQJUJed0NATpaxmW5q0IJsEMq4wtkCVH0QitTofouUnzh4P/OEDF8eDwVNJd1E9Az+XcHRZUjmaTyh0rFfcuXksz5ZdbMGYD+FuHwyZnZ3l2xOEs8zcLzh/8Fl4CO3evPtPTVpDSe+Ohf0PV8dLEDBF47+RCU9d5latMks2V/AnIxupLk="
after_success:
  - coveralls
  # create deploy data
  - mkdir -p packages
  - echo "Travis CI build # $TRAVIS_BUILD_NUMBER" >> packages/number.txt
  - tar czf packages/releases-$TRAVIS_BUILD_NUMBER.tar.gz $(ls -I packages)
  - zip -q packages/releases-$TRAVIS_BUILD_NUMBER.zip -r $(ls -I packages)
  # push to git
  - git config --global user.name "Travis CI"
  - git config --global user.email "ideuchi@gmail.com"
  - git add -A
  - git commit -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER"
  - git push https://$GH_TOKEN@github.com/ideuchi/python-test.git HEAD:master
notifications:
  slack:
    secure: ffI3t/tNZkLXBy32wRalJtQAsXbZd5wmybFxC7R2AyuwHVVT6Qi1odYig6xGcyRUMcChrrLXiQxVfVaGcmbpcnJCJtDbqT6Bt4IGv1v/96RvL3x0HOQ5xzBa2QprtTbYpKERgcdW65WTLx6lW+CnvUbFTOW2eZhTl6RuGWYMuv9gPzHDO+lCP9lSYbZ21tRdtlyEMMk5NHIHcb0j8slgh1IP8g/L8cgyGaj+iXclgLe7wnIn3Nh2uO0vLPlbF1a9UAYSo/V+1U34kKyv9KOtscG8zvTHcS+rgRJa2axS1m9GpM/qgZaDXiylyNBKzWJe30++vocQVDa2u4Gi2ReLVWXNHCIkQbO2Ib4TXn6DSQPDlgJpX3trg13asByx9Y6W1DZ0264t82A9rqLfWMl4mGwgBFpewYpFFDiw2T5c5iwNYe0q5s0zmDDbuy4AQJih8wtSh2pNECGi2ZH6z4ihAzCB7X43woXO6YzdZLQqAUjmo7US7HLeVK6KfqYFXVayAddho9l+b6B6law8+igwYzBsTC4YEMSxmk5R1z6N/WU5xgBECSq06H0KlIHJowng8PHQTryVUG/ceovdh5m1m9vSOqU0LsA1htPvvXZmaEC58jq1BxnftCGX9TZNR3YvBWB8D0SHjOHVTZjRucfqrzK4h98mUZNAw5vXG74sMlA=
