language: python

python:
 - 3.3
 - 3.4

install:
 - pip install coveralls

script:
 - coverage run --source=hoge_test setup.py test

after_success:
 - coveralls

notifications:
 slack: 'ideuchi:xoxp-341994756375-340247715712-340989358162-fbdc0667953105b687a310056287f140#development 

